apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-pagamentos-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sistema-pagamentos-mock
  template:
    metadata:
      labels:
        app: sistema-pagamentos-mock
    spec:
      containers:
        - name: sistema-pagamentos-mock
          image: rm355416/sistema-pagamentos-mock:latest
          ports:
            - containerPort: 5001