apiVersion: v1
kind: Service
metadata:
  name: sistema-pagamentos-mock-service
spec:
  selector:
    app: sistema-pagamentos-mock
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer